version: '3.9'
services:
#  front:
#    image:
#    environment:
#      -
#    depends_on:
#      - back

  back:
    image: redbird127/rtback
    restart: always
    ports:
      - 8080:8080
    environment:
      - PORT=8080